### ISSUE TITLE
Error | pls fix 

### ISSUE THREAD

**Issue by ZyvoksCode** [zachariapopcorn/backup-bot#2]
serverName;
2:06 PM
            ^
2:06 PM
2:06 PM
SyntaxError: Unexpected token ;
2:06 PM
    at new Script (vm.js:80:7)
2:06 PM
    at createScript (vm.js:274:10)
2:06 PM
    at Object.runInThisContext (vm.js:326:10)
2:06 PM
    at Module._compile (internal/modules/cjs/loader.js:664:28)
2:06 PM
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
2:06 PM
    at Module.load (internal/modules/cjs/loader.js:600:32)
2:06 PM
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
2:06 PM
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
2:06 PM
    at Module.require (internal/modules/cjs/loader.js:637:17)
2:06 PM
    at require (internal/modules/cjs/helpers.js:22:18)
2:06 PM

**Comment by zachariapopcorn** [comment]
I think it's because you have an older version of node and npm. Try running npm on 6.9.0 and node on 12.6.0

**Comment by ZyvoksCode** [comment]
Can you dm me on discord, I’d appreciate that a ton, I’ve been running it on Node 12

**Comment by zachariapopcorn** [comment]
Weird, as when I was testing everything, it worked fine in terms of syntax
Can you please run npm -v and node -v in the console and send the thing here?

**Comment by zachariapopcorn** [comment]
Hello?

**Comment by zachariapopcorn** [comment]
I'm going to close this issue as there's no response
